name: CI

on: [push, pull_request]

jobs:
  lint:
    name: Lint
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: install dependencies
        run: npm ci
      - name: lint code
        run: npm run lint

  build:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        node: ['16']
    name: Tests - Node ${{ matrix.node }} (${{ matrix.platform }})
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: install dependencies
        run: npm ci --ignore-engines
      - name: run tests
        run: npm run test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3           

  release:
    name: do semantic release
    runs-on: 'ubuntu-latest'
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: install dependencies
        run: npm ci --ignore-engines --only=production    
      - name: release
        run: npx semantic-release --dry-run
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
